on:
  push:
    branches: [master]

jobs:
  test:
    name: "Run pichunter tests"
    runs-on: 'ubuntu-latest'
    env:
      LISP: sbcl-bin
    steps:
      - uses: actions/checkout@v2

      - name: start db
        run: |
          docker-compose up -d

      - uses: 40ants/setup-lisp@v1
        # with:
        #   asdf-system: pichunter
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: pichunter
